@baseUrl = http://localhost:8080/api

###
#Create Post

POST {{baseUrl}}/posts
Accept: application/json
Content-Type: application/json

{
    "name": "Sample Post",
    "content": "This is the content of the post.",
    "postedBy": "John",
    "img": "https://example.com/image.jpg",
    "tags": ["tag1", "tag2"]
}

###
#Get Posts

GET {{baseUrl}}/posts
Accept: application/json
Content-Type: application/json

###
#Get Post By Id

GET {{baseUrl}}/posts/1
Accept: application/json
Content-Type: application/json

###
#Like Post By Id

PUT {{baseUrl}}/posts/1/like
Accept: application/json
Content-Type: application/json

###
#Like Post By Id

POST {{baseUrl}}/comments/create?postId=1&postedBy=Teste
Accept: application/json
Content-Type: application/json

{
    "content": "This is my comment!"
}
